### ISSUE TITLE
undefined method error

### ISSUE THREAD

**Issue by flamingice** [mcmahoniel/slaxtract#1]
Hi, I get this error:

sudo ./slaxtract.rb 
./slaxtract.rb:6:in `<main>': undefined method `configure' for Slack:Module (NoMethodError)

**Comment by mcmahoniel** [comment]
Hi @flamingice. :wave: 

You'll want to make sure you run `gem install slack-api` prior to running the script. If you've already done that, you might be hitting a different set of gems since you're prefixing your command with `sudo`, as that runs as `root` vs. the current user.

First, make sure them gem is installed. You can confirm that with `gem list | grep slack`. If it _is_ installed, make sure you're in the correct user when you run the command. For example, `./slaxtract.rb` instead of `sudo ./slaxtract.rb`.

Let me know how that turns out! :+1:

**Comment by flamingice** [comment]
Hi, slack-api was not installed correctly, I had to sudo apt-get install
ruby-dev and then do sudo gem install slack-api.

gem list | grep slack:
slack (0)
slack-api (1.1.6)

I still get this error though (with and without sudo):
./slaxtract.rb:6:in `<main>': undefined method `configure' for Slack:Module
(NoMethodError)


2015-09-23 22:02 GMT+02:00 Daniel James McMahon <notifications@github.com>:

**Comment by mcmahoniel** [comment]
Rather than using the global Ruby installed by your OS's package manager, you'll probably have better luck installing [RVM](https://rvm.io/) or [rbenv](https://github.com/sstephenson/rbenv).

Once you've got one of those set up, I'd recommend installing a current version of Ruby (like 2.2.3) and installing the `slack-api` gem within that specific gemset.

For example, with RVM, you would do `rvm install 2.2.3` followed by `rvm use 2.2.3 --default`.

At that point, if you did `which ruby` you should see something like `/home/flamingice/.rvm/rubies/ruby-2.2.3/bin/ruby` instead of something global like `/usr/bin/ruby`.

Then you can `gem install slack-api` and try and run `./slaxtract.rb` again.

Good luck! :smiley_cat:

**Comment by flamingice** [comment]
That worked well with RVM, thank you!

2015-09-24 0:30 GMT+02:00 Daniel James McMahon <notifications@github.com>:
